import { Injectable, OnModuleInit, OnModuleDestroy } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

/**
 * Extended PrismaClient interface with type declarations for the models
 * This helps TypeScript understand the schema models even if they're
 * not properly generated by Prisma
 */
interface PrismaModels {
  teamCollection: any;
  teamEnvironment: any;
  teamRequest: any;
  userCollection: any;
  userRequest: any;
  userEnvironment: any;
  userHistory: any;
  userSettings: any;
  account: any;
}

@Injectable()
export class PrismaService
  extends PrismaClient
  implements OnModuleInit, OnModuleDestroy
{
  // These properties are added at runtime by Prisma
  // We're just adding type information for TypeScript
  public readonly teamCollection!: PrismaModels['teamCollection'];  
  public readonly teamEnvironment!: PrismaModels['teamEnvironment'];
  public readonly teamRequest!: PrismaModels['teamRequest'];
  public readonly userCollection!: PrismaModels['userCollection'];
  public readonly userRequest!: PrismaModels['userRequest'];
  public readonly userEnvironment!: PrismaModels['userEnvironment'];
  public readonly userHistory!: PrismaModels['userHistory'];
  public readonly userSettings!: PrismaModels['userSettings'];
  public readonly account!: PrismaModels['account'];

  constructor() {
    super({
      log: ['error', 'warn'],
    });
  }

  async onModuleInit() {
    await this.$connect();
  }

  async onModuleDestroy() {
    await this.$disconnect();
  }
}
