-- -- This is a custom migration file which is not generated by Prisma.
-- -- The aim of this migration is to add text search indices to the TeamCollection and TeamRequest tables.

-- -- Enable full-text search catalog (run once per database, if not already enabled)
-- CREATE FULLTEXT CATALOG ftCatalog AS DEFAULT;

-- -- Create full-text index for TeamCollection.title
-- CREATE FULLTEXT INDEX ON "TeamCollection"(title) KEY INDEX "TeamCollection_pkey";

-- -- Create full-text index for TeamRequest.title
-- CREATE FULLTEXT INDEX ON "TeamRequest"(title) KEY INDEX "TeamRequest_pkey";

